# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='slug',
            field=models.SlugField(default='teste', max_length=100, verbose_name='Identificador'),
        ),
    ]
