# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topico_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='forum.Topico', verbose_name='Tópico'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='mensagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Mensagem'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
